language: python

compiler:
  - gcc

sudo: false #true

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: "3.6-dev"
    - python: "nightly"

  allow_failures:
    - python: "3.6-dev"
    - python: "nightly"


cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-5
      - binutils
      - cmake
      - graphviz
      - python-pip

#before_install:
#  #- sudo ln -fs /usr/bin/gfortran-5 /usr/bin/gfortran && gfortran --version
#  #- export PATH=".:$PATH"
#  - gcc -v
#  - gfortran -v

# command to install dependencies
install:
    - |
      if [[ ! -d "$HOME/.local/bin" ]]; then
        mkdir "$HOME/.local/bin"
      fi
    - export PATH="$HOME/.local/bin:$PATH"
    - export FC=/usr/bin/gfortran-5
    - ln -fs /usr/bin/gfortran-5 "$HOME/.local/bin/gfortran" && gfortran --version
    - ls -l /usr/bin/gfortran-5
    - if [[ $TRAVIS_PYTHON_VERSION < 3.5 ]];
      then pip install -r requirements2-34.travis.txt;
      else pip install -r requirements.travis.txt;
      fi
    - pip install https://github.com/modflowpy/flopy/zipball/develop
    - pip install nose-timer
    - pip install coveralls

# command to run tests
script: 
    - export PYTHONPATH=$PYTHONPATH:.
    - nosetests -v --with-id --with-timer -w ./autotest --with-coverage --cover-package=pymake
after_success:
    - coveralls
